version: 2.1

orbs:
  atscm:
    executors:
      node:
        docker:
          - image: circleci/node:12
      browsers:
        docker:
          - image: circleci/node:12-browsers
    commands:
      attach:
        steps:
          - checkout:
              path: /home/circleci/project
          - attach_workspace:
              at: /home/circleci/project
      git-login:
        steps:
          - run:
              name: Setting up git user
              command: git config --global user.email ci@ls-age.com && git config --global user.name "ls-age CI"

jobs:
  install:
    executor: atscm/node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v3-npm-deps-{{ checksum "package-lock.json" }}
            - v3-npm-deps
      - run:
          name: Installing npm dependencies
          environment:
            CYPRESS_INSTALL_BINARY: '0'
          command: npm ci
      - save_cache:
          key: v3-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    executor: atscm/node
    steps:
      - atscm/attach
      - run:
          name: Fetching data
          command: npm run fetch-data
      - run:
          name: Exporting app
          command: npm run export
      - persist_to_workspace:
          root: .
          paths:
            - __sapper__
            - src/data
            - src/node_modules

  lint:
    executor: atscm/node
    steps:
      - atscm/attach
      - run:
          name: Lint sources
          command: npm run lint -- --format junit --output-file ~/reports/eslint.xml
      - run:
          name: Check formatting
          command: npm run format -- --check
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports

  validate:
    executor: atscm/node
    steps:
      - atscm/attach
      - run:
          name: Run svelte-check
          command: npm run validate

  test:
    docker:
      - image: cypress/included:4.5.0
    working_directory: /home/circleci/project
    steps:
      - atscm/attach
      - restore_cache:
          keys:
            - v3-npm-deps-{{ checksum "package-lock.json" }}
            - v3-npm-deps
      # - run:
      #     name: Put Cypress binary in place
      #     command: |
      #       mkdir -p /root/.cache
      #       mv /home/circleci/.cache/Cypress /root/.cache/Cypress
      - run:
          name: Running tests
          command: npm run test:ci
      - store_test_results:
          path: test/report
      - store_artifacts:
          path: test/report

  deploy:
    executor: atscm/node
    steps:
      - atscm/attach
      - atscm/git-login
      - run:
          name: Deploying to github pages
          command: |
            git log -1 --pretty=%B > ../message
            git clone git@github.com:atSCM/atscm.github.io.git ../pages
            cd ../pages
            git rm -rf .
            cp -r ../project/__sapper__/export/. .
            git add .
            git commit -m "$(cat ../message) [ci skip]"
            git push origin master
            cd ../project

  lighthouse:
    executor: atscm/browsers
    steps:
      - checkout
      - atscm/git-login
      - restore_cache:
          keys:
            - v1-lighthouse-cache
      - run:
          name: Update lighthouse badges
          command: npx lighthouse-badges -o docs/assets -u https://atscm.github.io
      - save_cache:
          key: v1-lighthouse-cache
          paths:
            - ~/.npm
      - run:
          name: Commit lighthouse badges
          command: |
            git add docs/assets
            if git diff --name-only --cached --exit-code; then
              echo "Nothing to commit";
            else
              git commit -m "docs(readme): Update lighthouse badges [ci skip]

              $(git log -1 --pretty=%B)"
              git push origin $CIRCLE_BRANCH
            fi

workflows:
  version: 2

  default:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install
      - validate:
          requires:
            - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
            - lint
            - validate
          filters:
            branches:
              only:
                - master
      - lighthouse:
          requires:
            - deploy
